<Project>
  <ItemGroup>
    <!-- Refit exception handling -->
    <PackageVersion Include="Refit" Version="15.2.0" />

    <!-- Authentication -->
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />

    <!-- ASP.NET Core OpenAPI -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />

    <!-- Entity Framework Core -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />

    <!-- Npgsql -->
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />

    <!-- Serilog -->
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Enrichers.Span" Version="3.1.0" />
    <PackageVersion Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />

    <!-- WolverineFx -->
    <PackageVersion Include="JasperFx" Version="2.63.1" />
    <PackageVersion Include="WolverineFx" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.RuntimeCompilation" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.EntityFrameworkCore" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.FluentValidation" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.Http" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.Http.FluentValidation" Version="6.33.0" />
    <PackageVersion Include="WolverineFx.Postgresql" Version="6.33.0" />
  </ItemGroup>
</Project>
