<Project>
  <ItemGroup>
    <!-- Testing Framework -->
    <PackageVersion Include="xunit.v3.extensibility.core" Version="4.0.0" />

    <!-- Integration Testing -->
    <PackageVersion Include="Alba" Version="8.5.3" />
    <PackageVersion Include="Respawn" Version="7.0.0" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />

    <!-- End-To-End Testing -->
    <PackageVersion Include="Aspire.Hosting.Testing" Version="13.5.3" />
  </ItemGroup>
</Project>